# src/AppBundle/Resources/config/admin.yml

services:
    app.admin.recurso:
        class: Admin\AdminBundle\Admin\RecursoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Recurso" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Recurso
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]

    app.admin.editorial:
          class: Admin\AdminBundle\Admin\EditorialAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Content", label: "Editorial" }
          arguments:
              - ~
              - Admin\AdminBundle\Entity\Editorial
              - ~
          calls:
              - [ setTranslationDomain, [AdminAdminBundle]]